### ISSUE TITLE
Token失效出现预期外异常

### ISSUE THREAD

**Issue by Dev-Flo200** [shiwei-Ren/smpe-admin#25]
### 登陆admin账户后后删除token

```java
 java.lang.NumberFormatException: For input string: "admin"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at marchsoft.modules.security.security.TokenFilter.doFilter(TokenFilter.java:65)
```

**Comment by shiwei-Ren** [comment]
#### 原因
token异常清除缓存的策略出现了小bug

#### 解决
1. 在TokenProvider添加如下方法：
```
   /**
     * description:获取token的主题Subject信息
     *
     * @param token /
     * @return /
     * @author RenShiWei
     * Date: 2020/12/10 20:22
     */
    public String getSubject(String token) {
        Claims claims = getClaims(token);
        return claims.getSubject();
    }
```

2. 修改TokenFilter的doFilter()方法——主要将`userCacheClean.cleanUserCache(Long.parseLong(tokenProvider.getClaims(token).get(TokenProvider.AUTHORITIES_KEY).toString()));`
修改为
`userCacheClean.cleanUserCache(Long.parseLong(tokenProvider.getSubject(token)));`
```
    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain)
            throws IOException, ServletException {
        HttpServletRequest httpServletRequest = (HttpServletRequest) servletRequest;
        String token = resolveToken(httpServletRequest);
        // 对于 Token 为空的不需要去查 Redis
        if (StrUtil.isNotBlank(token)) {
            OnlineUserDto onlineUserDto = null;
            boolean cleanUserCache = false;
            try {
                //从redis中获取一条用户信息
                onlineUserDto = onlineUserService.getOne(properties.getOnlineKey() + token);
            } catch (ExpiredJwtException e) {
                log.error(e.getMessage());
                cleanUserCache = true;
            } finally {
                //出现异常或者用户信息为空时，清除用户缓存
                // modify @RenShiWei 2020/11/24 description:用户信息缓存在map中（java内存） ——> redis
                // modify @RenShiWei 2020/12/10 description:改变cleanUserCache的策略
                if (cleanUserCache || Objects.isNull(onlineUserDto)) {
                    userCacheClean.cleanUserCache(Long.parseLong(tokenProvider.getSubject(token)));
                }
            }
            // token合法
            if (onlineUserDto != null && StringUtils.hasText(token)) {
                //获取token认证信息
                Authentication authentication = tokenProvider.getAuthentication(token);
                //信息存储到security上下文
                SecurityContextHolder.getContext().setAuthentication(authentication);
                // Token 续期
                tokenProvider.checkRenewal(token);
            }
        }
        filterChain.doFilter(servletRequest, servletResponse);
    }
```

**Comment by Dev-Flo200** [comment]
问题可解决 ：)

**Comment by shiwei-Ren** [comment]
ok
